# Generated by Django 4.1.5 on 2023-01-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='filter_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('100 TO 300', '100 TO 300'), ('300 TO 500', '300 TO 500'), ('500 TO 700', '500 TO 700'), ('500 TO 700', '500 TO 700'), ('700 TO 900', '700 TO 900')], max_length=68)),
            ],
        ),
    ]
